Add attendance and population scripts
DataScienceScotland/school-information-dashboard pull request #5
Opened 2022-07-22 14:19 UTC by LauraStott

Please check this

2022-07-25 11:10 UTC, alicebyers5 requested changes
Hi Laura,

These scripts look great and seem to be mostly working - just a couple of wee bits that need changed and some suggested (but non-essential) changes too. I've added comments on individuals lines - happy for us to go through on a call so you can see how to make the changes on GitHub. 

One general question I had was about the coding of missing values: I know these are already coded as x/z/c in the attendance data, and you do this in the code for the population data - would also having the numeric value columns be useful for making the charts? (Like the attainment data files where we have a value column and a value_label column). Maybe not and we can always add in later if we change our mind but just thought I'd check.

Thanks,
Alice

2022-07-25 14:48 UTC, alicebyers5 commented on code/03_attendance.R
> +  mutate(student_stage = replace_na(student_stage, "All Stages")) %>%
```suggestion
  mutate(stage = replace_na(stage, "All Stages")) %>%
```

2022-07-25 15:01 UTC, LauraStott commented on code/04_population.R
> +         ptr = recode_missing_values(ptr, label = TRUE)) %>%
I think it would be useful to have the numeric columns for the charts :)

2022-07-26 10:25 UTC, alicebyers5 approved these changes
Hi Laura, thanks for making those changes. We can add the numeric value columns in another branch as realise the `recode_missing_values` function isn't merged with this code yet. We can discuss at our meeting.

Thanks,
Alice

2022-07-26 10:25 UTC, merged